/-
Copyright (c) 2026 Riccardo Brasca. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Riccardo Brasca
-/

module

public import PadicModForms.ModP.Graded
public import PadicModForms.ModP.Hasse
public import PadicModForms.ModP.Ramanujan
import Mathlib.RingTheory.MvPolynomial.EulerIdentity

/-!
# Ramanujan's derivation and the differential identity

Ramanujan's identities say that `Θ = q d/dq` does not preserve the ring generated by `E₄` and
`E₆`, but that it does so modulo `E₂`. This is expressed by the derivation `δ` of
`(ZMod p)[X₀, X₁]` sending `X₀ ↦ -4X₁` and `X₁ ↦ -6X₀²`, together with the identity
`12 Θ (evalE₄E₆ModP F) = w E₂ModP evalE₄E₆ModP F + evalE₄E₆ModP (δ F)` for `F` weighted
homogeneous of weight `w`.

This is the mod-`p` form of Serre's differential identity, and the mechanism by which the
Ramanujan identities produce information about the Hasse invariant.

## Main definitions

* `ModularForm.δModP`: Ramanujan's derivation `δ`, with `δ X₀ = -4X₁` and `δ X₁ = -6X₀²`.

## Main results

* `ModularForm.Θ_evalE₄E₆ModP`: the chain rule for `Θ ∘ evalE₄E₆ModP`.
* `ModularForm.twelve_Θ_evalE₄E₆ModP`: the differential identity
  `12 Θ (φ F) = w E₂ModP φ F + φ (δ F)` for `F` weighted homogeneous of weight `w`.
* `ModularForm.isWeightedHomogeneous_δModP`: `δ` raises the weight by `2`.
* `ModularForm.isWeightedHomogeneous_δModP_hasseInvPoly`: `δ hasseInvPoly` has weight
  `p + 1`.
* `ModularForm.evalE₄E₆ModP_δModP_hasseInvPoly`: the evaluation of `δ hasseInvPoly`
  is `E₂ModP`.
* `ModularForm.δModP_sq_hasseInvPoly`: the Hasse polynomial satisfies
  `δ² hasseInvPoly = -X₀ hasseInvPoly`.
-/

@[expose] public noncomputable section

open EisensteinSeries MvPolynomial
open PowerSeries hiding C X

namespace ModularForm

variable {p n : ℕ} [Fact p.Prime] (F : MvPolynomial (Fin 2) (ZMod p))

/-! ### Ramanujan's derivation -/

/-- **Ramanujan's derivation** `δ` on `(ZMod p)[X₀, X₁]`, the unique derivation with
`δ X₀ = -4X₁` and `δ X₁ = -6X₀²`. Under `evalE₄E₆ModP` it measures the failure of `Θ` to
preserve the ring generated by `E₄` and `E₆`; see `twelve_Θ_evalE₄E₆ModP`. -/
def δModP :
    Derivation (ZMod p) (MvPolynomial (Fin 2) (ZMod p)) (MvPolynomial (Fin 2) (ZMod p)) :=
  mkDerivation _ ![-4 * X 1, -6 * X 0 ^ 2]

@[simp]
theorem δModP_X_zero : δModP (X 0 : MvPolynomial (Fin 2) (ZMod p)) = -4 * X 1 := by
  simp [δModP]

@[simp]
theorem δModP_X_one : δModP (X 1 : MvPolynomial (Fin 2) (ZMod p)) = -6 * X 0 ^ 2 := by
  simp [δModP]

/-- `δ = -4X₁ ∂/∂X₀ - 6X₀² ∂/∂X₁`, as an identity of derivations. -/
theorem δModP_eq :
    (δModP : Derivation (ZMod p) (MvPolynomial (Fin 2) (ZMod p)) (MvPolynomial (Fin 2) (ZMod p))) =
      (-4 * X 1 : MvPolynomial (Fin 2) (ZMod p)) • pderiv 0 -
        (6 * X 0 ^ 2 : MvPolynomial (Fin 2) (ZMod p)) • pderiv 1 :=
  derivation_ext fun i ↦ by fin_cases i <;> simp

/-- `δ = -4X₁ ∂/∂X₀ - 6X₀² ∂/∂X₁`, evaluated at a polynomial. -/
theorem δModP_apply : δModP F = -4 * X 1 * pderiv 0 F - 6 * X 0 ^ 2 * pderiv 1 F := by
  simp [δModP_eq, smul_eq_mul, mul_assoc]

/-! ### The differential identity -/

/-- The chain rule for the evaluation at `E₄` and `E₆` modulo `p`. -/
theorem Θ_evalE₄E₆ModP : Θ (evalE₄E₆ModP F) = evalE₄E₆ModP (pderiv 0 F) * Θ E₄ModP +
    evalE₄E₆ModP (pderiv 1 F) * Θ E₆ModP := by
  induction F using MvPolynomial.induction_on with
  | C a => simp
  | add F G hF hG => simp only [map_add, hF, hG]; ring
  | mul_X F i hF =>
      rw [map_mul, Derivation.leibniz]
      fin_cases i <;> simp [hF] <;> ring

theorem twelve_Θ_evalE₄E₆ModP_chain : 12 * Θ (evalE₄E₆ModP F) =
    evalE₄E₆ModP (pderiv 0 F) * (12 * Θ E₄ModP) + evalE₄E₆ModP (pderiv 1 F) * (12 * Θ E₆ModP) := by
  rw [Θ_evalE₄E₆ModP]; ring

/-- The differential identity for an arbitrary polynomial: the weight is replaced by the weighted
Euler operator `4X₀ ∂/∂X₀ + 6X₁ ∂/∂X₁`, which on a weighted homogeneous polynomial of weight `n` is
multiplication by `n`. -/
theorem twelve_Θ_evalE₄E₆ModP_eq : 12 * Θ (evalE₄E₆ModP F) =
    E₂ModP * evalE₄E₆ModP (4 * X 0 * pderiv 0 F + 6 * X 1 * pderiv 1 F) +
      evalE₄E₆ModP (δModP F) := by
  rw [twelve_Θ_evalE₄E₆ModP_chain, twelve_Θ_E₄ModP, twelve_Θ_E₆ModP, δModP_apply]
  grind [map_ofNat, evalE₄E₆ModP_X_zero, evalE₄E₆ModP_X_one]

variable {F}

/-- Euler's identity for the weights `(4, 6)`: on a weighted homogeneous polynomial of weight `n`
the operator `4X₀ ∂/∂X₀ + 6X₁ ∂/∂X₁` is multiplication by `n`. -/
theorem euler_E₄E₆Weights (hF : IsWeightedHomogeneous E₄E₆Weights F n) :
    4 * X 0 * pderiv 0 F + 6 * X 1 * pderiv 1 F = (n : MvPolynomial (Fin 2) (ZMod p)) * F := by
  have h := hF.sum_weight_X_mul_pderiv
  simp [E₄E₆Weights, nsmul_eq_mul] at h
  grind

/-- **The differential identity**: if `F` is weighted homogeneous of weight `n`, then
`12 Θ (φ F) = n E₂ModP φ F + φ (δ F)`, where `φ = evalE₄E₆ModP`. -/
theorem twelve_Θ_evalE₄E₆ModP (hF : IsWeightedHomogeneous E₄E₆Weights F n) :
    12 * Θ (evalE₄E₆ModP F) =
      (n : (ZMod p)⟦X⟧) * (E₂ModP * evalE₄E₆ModP F) + evalE₄E₆ModP (δModP F) := by
  rw [twelve_Θ_evalE₄E₆ModP_eq, euler_E₄E₆Weights hF, map_mul, map_natCast]
  ring

/-! ### `δ` raises the weight by two -/

/-- Ramanujan's derivation raises the weight by `2`: if `F` is weighted homogeneous of weight
`n`, then `δ F` is weighted homogeneous of weight `n + 2`. -/
theorem isWeightedHomogeneous_δModP (hF : IsWeightedHomogeneous E₄E₆Weights F n) :
    IsWeightedHomogeneous E₄E₆Weights (δModP F) (n + 2) := by
  have hX₀ := isWeightedHomogeneous_X (ZMod p) E₄E₆Weights 0
  have hX₁ := isWeightedHomogeneous_X (ZMod p) E₄E₆Weights 1
  rw [δModP_apply]
  refine IsWeightedHomogeneous.sub ?_ ?_
  · rcases lt_or_ge n 4 with h | h
    · rw [hF.pderiv_eq_zero (by simpa using h), mul_zero]
      exact isWeightedHomogeneous_zero ..
    · obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le h
      rw [mul_assoc, show (-4 : MvPolynomial (Fin 2) (ZMod p)) = C (-4) by simp [map_ofNat],
        show 4 + m + 2 = 6 + m by omega]
      exact (hX₁.mul (hF.pderiv (by simp [add_comm]))).C_mul _
  · rcases lt_or_ge n 6 with h | h
    · rw [hF.pderiv_eq_zero (by simpa using h), mul_zero]
      exact isWeightedHomogeneous_zero ..
    · obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le h
      rw [mul_assoc, show (6 : MvPolynomial (Fin 2) (ZMod p)) = C 6 by rw [map_ofNat],
        show 6 + m + 2 = 4 * 2 + m by omega]
      exact ((hX₀.pow 2).mul (hF.pderiv (by simp [add_comm]))).C_mul _

/-! ### Differential equations for the Hasse invariant -/

/-- The Ramanujan derivative of `hasseInvPoly` is weighted homogeneous of weight `p + 1`. -/
theorem isWeightedHomogeneous_δModP_hasseInvPoly (hp : 5 ≤ p) :
    IsWeightedHomogeneous E₄E₆Weights (δModP (hasseInvPoly hp)) (p + 1) := by
  simpa [show p - 1 + 2 = p + 1 by omega] using
    isWeightedHomogeneous_δModP (hasseInvPoly_isWeightedHomogeneous hp)

/-- The evaluation of the Ramanujan derivative of the Hasse polynomial is `E₂ModP`. -/
theorem evalE₄E₆ModP_δModP_hasseInvPoly (hp : 5 ≤ p) :
    evalE₄E₆ModP (δModP (hasseInvPoly hp)) = E₂ModP :=
  sub_eq_zero.mp <| by
    simpa [sub_eq_add_neg, add_comm, evalE₄E₆ModP_hasseInvPoly hp, natCast_p_sub_one]
      using (twelve_Θ_evalE₄E₆ModP (hasseInvPoly_isWeightedHomogeneous hp)).symm

/-- The differential identity specialized to the Ramanujan derivative of `hasseInvPoly`. -/
theorem twelve_Θ_E₂ModP_eq_eval_δModP_sq_hasseInvPoly (hp : 5 ≤ p) :
    12 * Θ E₂ModP = E₂ModP * E₂ModP +
      evalE₄E₆ModP (δModP (δModP (hasseInvPoly hp))) := by
  simpa only [evalE₄E₆ModP_δModP_hasseInvPoly hp, natCast_p_add_one, one_mul] using
    twelve_Θ_evalE₄E₆ModP (isWeightedHomogeneous_δModP_hasseInvPoly hp)

/-- The second Ramanujan derivative of `hasseInvPoly` evaluates to `-E₄ModP`. -/
theorem evalE₄E₆ModP_δModP_sq_hasseInvPoly (hp : 5 ≤ p) :
    evalE₄E₆ModP (δModP (δModP (hasseInvPoly hp))) = -E₄ModP := by
  grind [twelve_Θ_E₂ModP_eq_eval_δModP_sq_hasseInvPoly hp, Θ_E₂ModP]

/-- The second Ramanujan derivative of `hasseInvPoly` is weighted homogeneous of weight
`p + 3`. -/
theorem isWeightedHomogeneous_δModP_sq_hasseInvPoly (hp : 5 ≤ p) :
    IsWeightedHomogeneous E₄E₆Weights (δModP (δModP (hasseInvPoly hp))) (p + 3) := by
  simpa [show p + 1 + 2 = p + 3 by omega] using
    isWeightedHomogeneous_δModP (isWeightedHomogeneous_δModP_hasseInvPoly hp)

/-- The polynomial `-X 0 * hasseInvPoly` is weighted homogeneous of weight `p + 3`. -/
theorem isWeightedHomogeneous_neg_X_zero_mul_hasseInvPoly (hp : 5 ≤ p) :
    IsWeightedHomogeneous E₄E₆Weights (-X 0 * hasseInvPoly hp) (p + 3) := by
  simpa [E₄E₆Weights, Matrix.cons_val_zero, show 4 + (p - 1) = p + 3 by omega] using
    (isWeightedHomogeneous_X _ E₄E₆Weights 0).neg.mul (hasseInvPoly_isWeightedHomogeneous hp)

/-- The Hasse polynomial satisfies the equation `δ² hasseInvPoly = -X₀ hasseInvPoly`. -/
theorem δModP_sq_hasseInvPoly (hp : 5 ≤ p) :
    δModP (δModP (hasseInvPoly hp)) = -X 0 * hasseInvPoly hp :=
  (SetLike.coe_eq_coe (p := (E₄E₆WeightedHomogeneous (p + 3) (ZMod p)))
    (x := ⟨_, isWeightedHomogeneous_δModP_sq_hasseInvPoly hp⟩)
    (y := ⟨_, isWeightedHomogeneous_neg_X_zero_mul_hasseInvPoly hp⟩)).2 <|
  (evalE₄E₆ModPAtWeight_inj hp).mp
    (by simp [evalE₄E₆ModP_δModP_sq_hasseInvPoly hp, evalE₄E₆ModP_hasseInvPoly hp])

end ModularForm
