/-
Copyright (c) 2026 Riccardo Brasca. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Riccardo Brasca
-/

module

public import PadicModForms.ModP.Graded
public import PadicModForms.ModP.Ramanujan
import Mathlib.RingTheory.MvPolynomial.EulerIdentity

/-!
# Ramanujan's derivation and the differential identity

Ramanujan's identities say that `Θ = q d/dq` does not preserve the ring generated by `E₄` and
`E₆`, but that it does so modulo `E₂`. This is expressed by the derivation `δ` of
`(ZMod p)[X₀, X₁]` sending `X₀ ↦ -4X₁` and `X₁ ↦ -6X₀²`, together with the identity
`12 Θ (evalE₄E₆ModP F) = w E₂ModP evalE₄E₆ModP F + evalE₄E₆ModP (δ F)` for `F` weighted
homogeneous of weight `w`.

This is the mod-`p` form of Serre's differential identity, and the mechanism by which the
Ramanujan identities produce information about the Hasse invariant.

## Main definitions

* `ModularForm.δModP`: Ramanujan's derivation `δ`, with `δ X₀ = -4X₁` and `δ X₁ = -6X₀²`.

## Main results

* `ModularForm.Θ_evalE₄E₆ModP`: the chain rule for `Θ ∘ evalE₄E₆ModP`.
* `ModularForm.twelve_Θ_evalE₄E₆ModP`: the differential identity
  `12 Θ (φ F) = w E₂ModP φ F + φ (δ F)` for `F` weighted homogeneous of weight `w`.
* `ModularForm.isWeightedHomogeneous_δModP`: `δ` raises the weight by `2`.
-/

@[expose] public noncomputable section

open EisensteinSeries MvPolynomial
open PowerSeries hiding C X

namespace ModularForm

variable {p n : ℕ} [Fact p.Prime] (F : MvPolynomial (Fin 2) (ZMod p))

/-! ### Ramanujan's derivation -/

/-- **Ramanujan's derivation** `δ` on `(ZMod p)[X₀, X₁]`, the unique derivation with
`δ X₀ = -4X₁` and `δ X₁ = -6X₀²`. Under `evalE₄E₆ModP` it measures the failure of `Θ` to
preserve the ring generated by `E₄` and `E₆`; see `twelve_Θ_evalE₄E₆ModP`. -/
def δModP :
    Derivation (ZMod p) (MvPolynomial (Fin 2) (ZMod p)) (MvPolynomial (Fin 2) (ZMod p)) :=
  mkDerivation _ ![-4 * X 1, -6 * X 0 ^ 2]

@[simp]
theorem δModP_X_zero : δModP (X 0 : MvPolynomial (Fin 2) (ZMod p)) = -4 * X 1 := by
  simp [δModP]

@[simp]
theorem δModP_X_one : δModP (X 1 : MvPolynomial (Fin 2) (ZMod p)) = -6 * X 0 ^ 2 := by
  simp [δModP]

/-- `δ = -4X₁ ∂/∂X₀ - 6X₀² ∂/∂X₁`, as an identity of derivations. -/
theorem δModP_eq :
    (δModP : Derivation (ZMod p) (MvPolynomial (Fin 2) (ZMod p)) (MvPolynomial (Fin 2) (ZMod p))) =
      (-4 * X 1 : MvPolynomial (Fin 2) (ZMod p)) • pderiv 0 -
        (6 * X 0 ^ 2 : MvPolynomial (Fin 2) (ZMod p)) • pderiv 1 :=
  derivation_ext fun i ↦ by fin_cases i <;> simp

/-- `δ = -4X₁ ∂/∂X₀ - 6X₀² ∂/∂X₁`, evaluated at a polynomial. -/
theorem δModP_apply : δModP F = -4 * X 1 * pderiv 0 F - 6 * X 0 ^ 2 * pderiv 1 F := by
  simp [δModP_eq, smul_eq_mul, mul_assoc]

/-! ### The differential identity -/

/-- The chain rule for the evaluation at `E₄` and `E₆` modulo `p`. -/
theorem Θ_evalE₄E₆ModP : Θ (evalE₄E₆ModP F) = evalE₄E₆ModP (pderiv 0 F) * Θ E₄ModP +
    evalE₄E₆ModP (pderiv 1 F) * Θ E₆ModP := by
  induction F using MvPolynomial.induction_on with
  | C a => simp
  | add F G hF hG => simp only [map_add, hF, hG]; ring
  | mul_X F i hF =>
      rw [map_mul, Derivation.leibniz]
      fin_cases i <;> simp [hF] <;> ring

theorem twelve_Θ_evalE₄E₆ModP_chain : 12 * Θ (evalE₄E₆ModP F) =
    evalE₄E₆ModP (pderiv 0 F) * (12 * Θ E₄ModP) + evalE₄E₆ModP (pderiv 1 F) * (12 * Θ E₆ModP) := by
  rw [Θ_evalE₄E₆ModP]; ring

/-- The differential identity for an arbitrary polynomial: the weight is replaced by the weighted
Euler operator `4X₀ ∂/∂X₀ + 6X₁ ∂/∂X₁`, which on a weighted homogeneous polynomial of weight `n` is
multiplication by `n`. -/
theorem twelve_Θ_evalE₄E₆ModP_eq : 12 * Θ (evalE₄E₆ModP F) =
    E₂ModP * evalE₄E₆ModP (4 * X 0 * pderiv 0 F + 6 * X 1 * pderiv 1 F) +
      evalE₄E₆ModP (δModP F) := by
  rw [twelve_Θ_evalE₄E₆ModP_chain, twelve_Θ_E₄ModP, twelve_Θ_E₆ModP, δModP_apply]
  grind [map_ofNat, evalE₄E₆ModP_X_zero, evalE₄E₆ModP_X_one]

variable {F}

/-- Euler's identity for the weights `(4, 6)`: on a weighted homogeneous polynomial of weight `n`
the operator `4X₀ ∂/∂X₀ + 6X₁ ∂/∂X₁` is multiplication by `n`. -/
theorem euler_E₄E₆Weights (hF : IsWeightedHomogeneous E₄E₆Weights F n) :
    4 * X 0 * pderiv 0 F + 6 * X 1 * pderiv 1 F = (n : MvPolynomial (Fin 2) (ZMod p)) * F := by
  have h := hF.sum_weight_X_mul_pderiv
  simp [E₄E₆Weights, nsmul_eq_mul] at h
  grind

/-- **The differential identity**: if `F` is weighted homogeneous of weight `n`, then
`12 Θ (φ F) = n E₂ModP φ F + φ (δ F)`, where `φ = evalE₄E₆ModP`. -/
theorem twelve_Θ_evalE₄E₆ModP (hF : IsWeightedHomogeneous E₄E₆Weights F n) :
    12 * Θ (evalE₄E₆ModP F) =
      (n : (ZMod p)⟦X⟧) * (E₂ModP * evalE₄E₆ModP F) + evalE₄E₆ModP (δModP F) := by
  rw [twelve_Θ_evalE₄E₆ModP_eq, euler_E₄E₆Weights hF, map_mul, map_natCast]
  ring

/-! ### `δ` raises the weight by two -/

/-- Ramanujan's derivation raises the weight by `2`: if `F` is weighted homogeneous of weight
`n`, then `δ F` is weighted homogeneous of weight `n + 2`. -/
theorem isWeightedHomogeneous_δModP (hF : IsWeightedHomogeneous E₄E₆Weights F n) :
    IsWeightedHomogeneous E₄E₆Weights (δModP F) (n + 2) := by
  have hX₀ := isWeightedHomogeneous_X (ZMod p) E₄E₆Weights 0
  have hX₁ := isWeightedHomogeneous_X (ZMod p) E₄E₆Weights 1
  rw [δModP_apply]
  refine IsWeightedHomogeneous.sub ?_ ?_
  · rcases lt_or_ge n 4 with h | h
    · rw [hF.pderiv_eq_zero (by simpa using h), mul_zero]
      exact isWeightedHomogeneous_zero ..
    · obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le h
      rw [mul_assoc, show (-4 : MvPolynomial (Fin 2) (ZMod p)) = C (-4) by simp [map_ofNat],
        show 4 + m + 2 = 6 + m by omega]
      exact (hX₁.mul (hF.pderiv (by simp [add_comm]))).C_mul _
  · rcases lt_or_ge n 6 with h | h
    · rw [hF.pderiv_eq_zero (by simpa using h), mul_zero]
      exact isWeightedHomogeneous_zero ..
    · obtain ⟨m, rfl⟩ := Nat.exists_eq_add_of_le h
      rw [mul_assoc, show (6 : MvPolynomial (Fin 2) (ZMod p)) = C 6 by rw [map_ofNat],
        show 6 + m + 2 = 4 * 2 + m by omega]
      exact ((hX₀.pow 2).mul (hF.pderiv (by simp [add_comm]))).C_mul _

end ModularForm
