/-
Copyright (c) 2026 Riccardo Brasca. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Riccardo Brasca
-/

module

public import PadicModForms.ModP.Squarefree
public import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import PadicModForms.pLocalInt.Discriminant
import Mathlib.RingTheory.KrullDimension.Field
import Mathlib.RingTheory.KrullDimension.Polynomial

/-!
# The kernel of the evaluation at `E₄` and `E₆`

Let `p ≥ 5` and write `A = hasseInvPoly hp`, weighted homogeneous of weight `d = p - 1` with
`evalE₄E₆ModP A = 1`. We prove Swinnerton-Dyer's theorem that the kernel of `evalE₄E₆ModP` is
generated by `A - 1`, so that the algebra of mod-`p` modular forms is `(ZMod p)[X₀, X₁]/(A - 1)`.

The proof has two halves. First `A - 1` is irreducible: a factorization homogenizes, an auxiliary
variable of weight one filling each monomial up to the maximal weight occurring in it, to a
factorization of `T ^ d - A`, which is Eisenstein at any irreducible factor `π` of `A` — that `π`
occurs only once in `A` is the squarefreeness proved in `PadicModForms.ModP.Squarefree`. Then the
ideal `(A - 1)` is prime and contained in the kernel, and a strict containment would produce a
chain of four primes in a ring of Krull dimension `2`, the kernel not being maximal because the
image of `X₀³ - X₁²` is a nonzero nonunit of `(ZMod p)⟦q⟧`.

## Main results

* `ModularForm.irreducible_hasseInvPoly_sub_one`: `A - 1` is irreducible.
* `ModularForm.ker_evalE₄E₆ModP`: the kernel of `evalE₄E₆ModP` is generated by `A - 1`.
-/

@[expose] public noncomputable section

open Polynomial

namespace ModularForm

variable {p : ℕ} [Fact p.Prime] {P : MvPolynomial (Fin 2) (ZMod p)} {N : ℕ}

/-! ### An irreducible factor of the Hasse invariant -/

/-- The Hasse invariant, being neither zero nor a unit, has an irreducible factor `π`; since it is
squarefree, `π * π` does not divide it. -/
theorem exists_irreducible_dvd_hasseInvPoly (hp : 5 ≤ p) : ∃ π : MvPolynomial (Fin 2) (ZMod p),
    Irreducible π ∧ π ∣ hasseInvPoly hp ∧ ¬π * π ∣ hasseInvPoly hp := by
  obtain ⟨π, hπ, hπA⟩ := WfDvdMonoid.exists_irreducible_factor
    (not_isUnit_hasseInvPoly hp) (hasseInvPoly_ne_zero hp)
  exact ⟨π, hπ, hπA, fun h ↦ hπ.not_isUnit (hasseInvPoly_squarefree hp π h)⟩

/-! ### Eisenstein's criterion for `T ^ (p - 1) - A` -/

/-- `T ^ (p - 1) - A` is Eisenstein at an irreducible factor `π` of the Hasse invariant `A`: it is
monic, its intermediate coefficients vanish, and its constant coefficient `-A` is divisible by `π`
but not by `π ^ 2`. -/
theorem isEisensteinAt_X_pow_sub_C_hasseInvPoly (hp : 5 ≤ p) (hP : Irreducible P)
    (hPA : P ∣ hasseInvPoly hp) (hP2 : ¬P * P ∣ hasseInvPoly hp) :
    (X ^ (p - 1) - C (hasseInvPoly hp)).IsEisensteinAt (Ideal.span {P}) where
  leading := by
    rw [(monic_X_pow_sub_C _ (by lia)).leadingCoeff, Ideal.mem_span_singleton]
    exact fun h ↦ hP.not_isUnit (isUnit_of_dvd_one h)
  mem {n} hn := by
    rw [natDegree_X_pow_sub_C] at hn
    rw [coeff_sub, coeff_X_pow, ite_eq_right (by lia), coeff_C, Ideal.mem_span_singleton]
    split_ifs <;> simp_all
  notMem := by
    rw [coeff_sub, coeff_X_pow, ite_eq_right (by lia), coeff_C_zero, zero_sub,
      Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    exact fun h ↦ hP2 (by rwa [← dvd_neg, ← pow_two])

/-- **Eisenstein's criterion**: `T ^ (p - 1) - A` is irreducible in `(ZMod p)[X₀, X₁][T]`. -/
theorem irreducible_X_pow_sub_C_hasseInvPoly (hp : 5 ≤ p) (hP : Irreducible P)
    (hPA : P ∣ hasseInvPoly hp) (hπ2 : ¬P * P ∣ hasseInvPoly hp) :
    Irreducible (X ^ (p - 1) - C (hasseInvPoly hp)) :=
  (isEisensteinAt_X_pow_sub_C_hasseInvPoly hp hP hPA hπ2).irreducible
    ((Ideal.span_singleton_prime hP.ne_zero).2
      (UniqueFactorizationMonoid.irreducible_iff_prime.1 hP))
    (monic_X_pow_sub_C _ (by lia)).isPrimitive  (by rw [natDegree_X_pow_sub_C]; lia)

/-! ### Irreducibility of `A - 1` -/

open MvPolynomial hiding C X coeff monomial

/-- A weighted homogenization of positive degree, of a polynomial with nonzero constant
coefficient, is not a unit: its coefficient in that degree is the constant coefficient. -/
private theorem not_isUnit_weightedHomogenize (hN : 0 < N) (hP : constantCoeff P ≠ 0) :
    ¬IsUnit (weightedHomogenize E₄E₆Weights N P) := fun hunit ↦ by
  have hcoeff : (weightedHomogenize E₄E₆Weights N P).coeff N ≠ 0 := by
    simpa [constantCoeff_eq] using hP
  grind [natDegree_eq_zero_of_isUnit, le_natDegree_of_ne_zero hcoeff]

/-- A factor of the Hasse invariant minus one is nonzero in weight `0`, and its maximal weight is
positive unless it is a unit. -/
private theorem natDegree_toWeightPolynomial_pos (hP0 : P ≠ 0) (hPu : ¬IsUnit P) :
    0 < (toWeightPolynomial E₄E₆Weights P).natDegree := by
  rcases Nat.eq_zero_or_pos (toWeightPolynomial E₄E₆Weights P).natDegree with h | h
  · refine absurd ((h ▸ isWeightedHomogeneous_natDegree ?_).isUnit_of_ne_zero
      E₄E₆Weights_ne_zero hP0) hPu
    grind [natTrailingDegree_le_natDegree (toWeightPolynomial E₄E₆Weights P)]
  · exact h

/-- **The Hasse invariant minus one is irreducible.** A factorization `A - 1 = F * G` homogenizes,
in the maximal weights `r` and `s` of `F` and `G`, to a factorization of `A - T ^ (p - 1)`; both
homogenizations have positive degree because `F` and `G` have nonzero constant coefficients, and
this contradicts the irreducibility of `T ^ (p - 1) - A`. -/
theorem irreducible_hasseInvPoly_sub_one (hp : 5 ≤ p) : Irreducible (hasseInvPoly hp - 1) := by
  obtain ⟨P, hP, hPA, hP2⟩ := exists_irreducible_dvd_hasseInvPoly hp
  have hAhom := hasseInvPoly_isWeightedHomogeneous hp
  have hTP : toWeightPolynomial E₄E₆Weights (hasseInvPoly hp - 1) =
      monomial (p - 1) (hasseInvPoly hp) - 1 := by simp [toWeightPolynomial_eq_monomial_iff.2 hAhom]
  have hdeg : (toWeightPolynomial E₄E₆Weights (hasseInvPoly hp - 1)).natDegree = p - 1 := by
    grind [natDegree_sub_eq_left_of_natDegree_lt, natDegree_monomial_eq _ (hasseInvPoly_ne_zero hp),
      natDegree_monomial_eq _ (hasseInvPoly_ne_zero hp), natDegree_one]
  have hA1 : hasseInvPoly hp - 1 ≠ 0 := by grind
  refine ⟨fun hunit ↦ ?_, fun F G hFG ↦ ?_⟩
  · grind [natDegree_eq_zero_of_isUnit (hunit.map (toWeightPolynomial E₄E₆Weights))]
  by_contra! hcon
  set r := (toWeightPolynomial E₄E₆Weights F).natDegree with hr
  set s := (toWeightPolynomial E₄E₆Weights G).natDegree with hs
  suffices X ^ (p - 1) - C (hasseInvPoly hp) =
      (-weightedHomogenize E₄E₆Weights r F) * weightedHomogenize E₄E₆Weights s G by
    have hconst : constantCoeff F * constantCoeff G = -1 := by rw [← map_mul, ← hFG, map_sub,
      map_one, constantCoeff_eq, hAhom.coeff_eq_zero 0 (by grind), zero_sub]
    rcases (irreducible_X_pow_sub_C_hasseInvPoly hp hP hPA hP2).isUnit_or_isUnit this with h | h
    · exact not_isUnit_weightedHomogenize (natDegree_toWeightPolynomial_pos (by grind) hcon.1)
        (fun h0 ↦ by simp [h0] at hconst) ((IsUnit.neg_iff _).mp h)
    · exact not_isUnit_weightedHomogenize (natDegree_toWeightPolynomial_pos (by grind) hcon.2)
        (fun h0 ↦ by simp [h0] at hconst) h
  suffices weightedHomogenize E₄E₆Weights r F * weightedHomogenize E₄E₆Weights s G =
      C (hasseInvPoly hp) - X ^ (p - 1) by
    grind
  have hrs : r + s = p - 1 := by rw [hr, hs, ← natDegree_mul (toWeightPolynomial_ne_zero _
    (by grind)) (toWeightPolynomial_ne_zero _ (by grind)), ← map_mul, ← hFG, hdeg]
  rw [← weightedHomogenize_mul le_rfl le_rfl, hrs, ← hFG, map_sub,
    weightedHomogenize_of_isWeightedHomogeneous hAhom le_rfl, weightedHomogenize_one,
    Nat.sub_self, pow_zero, mul_one]

/-! ### The coefficient of `q` in the evaluation of `X₀³ - X₁²` -/

/-- The coefficient of `q` in `evalE₄E₆ModP (X₀³ - X₁²) = E₄³ - E₆² = 1728 Δ` is `1728`, which is
nonzero modulo `p` because `p ≥ 5`. -/
theorem coeff_one_evalE₄E₆ModP_X_zero_pow_three_sub_X_one_sq (hp : 5 ≤ p) :
    PowerSeries.coeff 1 (evalE₄E₆ModP
      ((MvPolynomial.X 0) ^ 3 - MvPolynomial.X 1 ^ 2)) = (1728 : ZMod p) := by
  suffices EisensteinSeries.E₄ModP ^ 3 - EisensteinSeries.E₆ModP ^ 2 =
      PowerSeries.map (pLocalInt.toZMod (p := p))
        (EisensteinSeries.E₄_int ^ 3 - EisensteinSeries.E₆_int ^ 2) by
    simp [evalE₄E₆ModP_X_zero_pow_three_sub_X_one_sq, this, ← smul_discriminant_int hp,
    coeff_discriminant_int_one hp, smul_eq_mul, map_ofNat]
  simp [EisensteinSeries.E₄ModP, EisensteinSeries.E₆ModP]

/-- The evaluation of `X₀³ - X₁²` is nonzero: its coefficient of `q` is `1728`, which is invertible
modulo `p` because `p ≥ 5`. -/
theorem evalE₄E₆ModP_X_zero_pow_three_sub_X_one_sq_ne_zero (hp : 5 ≤ p) :
    evalE₄E₆ModP (p := p) ((MvPolynomial.X 0) ^ 3 - MvPolynomial.X 1 ^ 2) ≠ 0 := fun h ↦ by
  have h1728 := coeff_one_evalE₄E₆ModP_X_zero_pow_three_sub_X_one_sq hp
  rw [h, map_zero] at h1728
  exact not_dvd_1728 hp ((ZMod.natCast_eq_zero_iff 1728 p).1 (by exact_mod_cast h1728.symm))

/-! ### The kernel of the evaluation is not maximal -/

/-- The kernel of `evalE₄E₆ModP` is not maximal: were it, the image of `X₀³ - X₁²`, being nonzero,
would be invertible, whereas its constant coefficient vanishes. -/
theorem not_isMaximal_ker_evalE₄E₆ModP (hp : 5 ≤ p) :
    ¬(RingHom.ker (evalE₄E₆ModP (p := p))).IsMaximal := fun hmax ↦ by
  obtain ⟨y, i, hi, hyi⟩ := hmax.exists_inv fun h ↦
    evalE₄E₆ModP_X_zero_pow_three_sub_X_one_sq_ne_zero hp (RingHom.mem_ker.1 h)
  have hunit := congrArg evalE₄E₆ModP hyi
  rw [map_add, map_mul, map_one, RingHom.mem_ker.1 hi, add_zero] at hunit
  grind [constantCoeff_evalE₄E₆ModP_X_zero_pow_three_sub_X_one_sq,
    congrArg PowerSeries.constantCoeff hunit]

/-! ### The ideal generated by `A - 1` -/

open Ideal

theorem hasseInvPoly_sub_one_ne_zero (hp : 5 ≤ p) : hasseInvPoly hp - 1 ≠ 0 :=
  (irreducible_hasseInvPoly_sub_one hp).ne_zero

/-- `A - 1` is prime, `(ZMod p)[X₀, X₁]` being a unique factorization monoid. -/
theorem prime_hasseInvPoly_sub_one (hp : 5 ≤ p) : Prime (hasseInvPoly hp - 1) :=
  irreducible_iff_prime.1 (irreducible_hasseInvPoly_sub_one hp)

/-- The ideal generated by `A - 1` is prime. -/
theorem isPrime_span_hasseInvPoly_sub_one (hp : 5 ≤ p) : (span {hasseInvPoly hp - 1}).IsPrime :=
  (span_singleton_prime (hasseInvPoly_sub_one_ne_zero hp)).2 (prime_hasseInvPoly_sub_one hp)

/-- The ideal generated by `A - 1` is contained in the kernel of the evaluation, since the
`q`-expansion of the Hasse invariant is `1`. -/
theorem span_hasseInvPoly_sub_one_le_ker (hp : 5 ≤ p) :
    span {hasseInvPoly hp - 1} ≤ RingHom.ker evalE₄E₆ModP :=
  (span_singleton_le_iff_mem _).2 (hasseInvPoly_sub_one_mem_ker hp)

/-! ### The Krull dimension bound -/

/-- A strict chain `⊥ < J < I` of prime ideals of `(ZMod p)[X₀, X₁]` cannot be continued: no prime
strictly contains `I`. Such a chain would be an `LTSeries` of length `3` in the prime spectrum,
whereas the Krull dimension is `2`. -/
theorem not_lt_of_bot_lt_of_lt {J I M : Ideal (MvPolynomial (Fin 2) (ZMod p))} (hJ : J.IsPrime)
    (hI : I.IsPrime) (hM : M.IsPrime) (hbot : ⊥ < J) (hJI : J < I) : ¬I < M := fun hIM ↦ by
  suffices 3 ≤ ringKrullDim (MvPolynomial (Fin 2) (ZMod p)) by norm_num at this
  refine Order.le_krullDim_iff.2
    ⟨⟨3, ![⟨⊥, Ideal.isPrime_bot⟩, ⟨J, hJ⟩, ⟨I, hI⟩, ⟨M, hM⟩], fun i ↦ ?_⟩, rfl⟩
  fin_cases i <;> assumption

/-! ### The kernel of the evaluation -/

/-- **Swinnerton-Dyer's theorem**: the kernel of the evaluation at `E₄` and `E₆` modulo `p` is
generated by `hasseInvPoly hp - 1`.

The ideal `J` generated by `A - 1` is prime and contained in the kernel `I`, which is prime as the
kernel of a map to a domain. Were the containment strict, `⊥ < J < I < M` for a maximal `M` above
`I` — such an `M` exists strictly above `I` because `I` is not maximal — would be a chain of four
primes, which the Krull dimension `2` of `(ZMod p)[X₀, X₁]` forbids. -/
theorem ker_evalE₄E₆ModP (hp : 5 ≤ p) : RingHom.ker evalE₄E₆ModP = span {hasseInvPoly hp - 1} := by
  refine le_antisymm ?_ (span_hasseInvPoly_sub_one_le_ker hp)
  by_contra hle
  have hI : (RingHom.ker (evalE₄E₆ModP (p := p))).IsPrime := RingHom.ker_isPrime _
  obtain ⟨M, hM, hIM⟩ := exists_le_maximal _ hI.ne_top
  exact not_lt_of_bot_lt_of_lt (isPrime_span_hasseInvPoly_sub_one hp) hI hM.isPrime
    (bot_lt_iff_ne_bot.2 fun h ↦ hasseInvPoly_sub_one_ne_zero hp (span_singleton_eq_bot.1 h))
    (lt_of_le_not_ge (span_hasseInvPoly_sub_one_le_ker hp) hle)
    (lt_of_le_of_ne hIM fun h ↦ not_isMaximal_ker_evalE₄E₆ModP hp (h ▸ hM))


end ModularForm
