/-
Copyright (c) 2026 Riccardo Brasca. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Riccardo Brasca
-/

module

public import Mathlib

public import PadicModForms.ForMathlib.IntLocalization
public import PadicModForms.ForMathlib.PowerSeriesTopology
public import PadicModForms.PAdic.Defs
public import PadicModForms.Rational.Basic
import PadicModForms.ForMathlib.EInt
import PadicModForms.ForMathlib.Padic
import PadicModForms.ForMathlib.SpecificLimits

/-!
# Basic results about p-adic modular forms and power series

This file develops the coefficientwise p-adic valuation on power series and records the basic
way in which a classical rational modular form gives a p-adic modular form.
-/

@[expose] public section

open Filter Topology PowerSeries Padic

open scoped PowerSeriesUniformConvergence

variable {p : ℕ} [hp : Fact p.Prime]

/-- A classical rational modular form gives a p-adic modular form after extending scalars. -/
theorem powerSeries_isPAdicModularForm_of_qExpansion_eq_map (p : ℕ) [Fact p.Prime]
    {g : ℚ⟦X⟧} (hg : ∃ k : ℤ, g.isModularForm k) :
    g.map (algebraMap ℚ ℚ_[p]) |>.isPAdicModularForm p := by
  rcases hg with ⟨k, f, hg⟩
  refine ⟨⟨fun _ ↦ g, fun _ ↦ k, fun i ↦ ⟨f, hg⟩, fun u hu ↦ ?_⟩⟩
  filter_upwards with i n
  simpa using refl_mem_uniformity hu

namespace PowerSeries.Padic

noncomputable local instance : UniformSpace (ℚ_[p]⟦X⟧) :=
  PowerSeries.WithUniformConvergence.uniformSpace

/-- The additive `p`-adic valuation of the `n`-th coefficient of a power series, viewed in the
extended integers `[-∞, ∞]`. -/
noncomputable abbrev coeffPadicValuation (n : ℕ) (f : ℚ_[p]⟦X⟧) : EInt :=
  Padic.addValuation (coeff n f)

/-- The valuation on `ℚ_[p]⟦X⟧`: for `f = ∑ aₙ Xⁿ` we set `v(f) = infₙ v_p(aₙ)`. -/
noncomputable def v (f : ℚ_[p]⟦X⟧) : EInt :=
  ⨅ n, coeffPadicValuation n f

theorem v_def (f : ℚ_[p]⟦X⟧) : v f = ⨅ n, (addValuation (coeff n f) : EInt) :=
  rfl

theorem v_le_coeffPadicValuation (f : ℚ_[p]⟦X⟧) (n : ℕ) : v f ≤ coeffPadicValuation n f :=
  iInf_le ..

theorem le_v_iff {m : EInt} {f : ℚ_[p]⟦X⟧} : m ≤ v f ↔ ∀ n : ℕ, m ≤ coeffPadicValuation n f :=
  le_iInf_iff

/-- A sequence of `p`-adic power series converges for the topology of uniform convergence of
coefficients iff the valuations of its differences from the limit tend to `∞`. -/
theorem tendsto_iff_v_sub_tendsto_nhds_top {F : ℕ → ℚ_[p]⟦X⟧} {f : ℚ_[p]⟦X⟧} :
    Tendsto F atTop (𝓝 f) ↔ Tendsto (fun n ↦ v (F n - f)) atTop (𝓝 (⊤ : EInt)) := by
  rw [WithUniformConvergence.tendsto_iff_tendstoUniformly,
    Metric.tendstoUniformly_iff, tendsto_eint_nhds_top_iff]
  refine ⟨fun h k ↦ ?_, fun h ε hε ↦ ?_⟩
  · have hp : (0 : ℝ) < p := mod_cast hp.1.pos
    filter_upwards [h _ (zpow_pos hp (-k))] with i hi
    exact le_v_iff.2 fun n ↦ (intCast_le_addValuation_iff_norm_le_pow k _).2
      (le_of_lt (by simpa [dist_eq_norm'] using hi n))
  · obtain ⟨k, hk⟩ := exists_zpow_neg_lt (b := (p : ℝ)) (mod_cast hp.1.one_lt) hε
    filter_upwards [h k] with i hi n
    rw [dist_eq_norm', ← map_sub]
    exact ((intCast_le_addValuation_iff_norm_le_pow k _).1 (le_v_iff.1 hi n)).trans_lt hk

theorem v_nonneg_iff {f : ℚ_[p]⟦X⟧} :
    0 ≤ v f ↔ ∃ g : ℤ_[p]⟦X⟧, g.map (algebraMap _ _) = f := by
  refine ⟨fun hf ↦ ?_, ?_⟩
  · let a : ℕ → ℤ_[p] := fun n ↦
      ⟨coeff n f, (zero_le_addValuation_iff_norm_le_one _).1 (le_v_iff.1 hf n)⟩
    exact ⟨.mk a, ext fun n ↦ by
      rw [PowerSeries.coeff_map, PowerSeries.coeff_mk, PadicInt.algebraMap_apply]⟩
  · rintro ⟨g, rfl⟩
    exact le_v_iff.2 fun n ↦ (zero_le_addValuation_iff_norm_le_one _).2
      (by simpa using (coeff n g).2)

/-- A rational power series has nonnegative `p`-adic valuation iff its coefficients come from the
localization of `ℤ` at the prime ideal generated by `p`. -/
theorem v_nonneg_iff_rat {f : ℚ⟦X⟧} :
    0 ≤ v (f.map (algebraMap ℚ ℚ_[p])) ↔
      ∃ g : (pLocalInt p)⟦X⟧, g.map (algebraMap _ _) = f := by
  refine ⟨fun hf ↦ ?_, ?_⟩
  · have hcoeff (n : ℕ) : coeff n f ∈ pLocalInt p :=
      (mem_pLocalInt_iff _).2 <| (zero_le_addValuation_ratCast_iff p (coeff n f)).1 <|
        by simpa using le_v_iff.1 hf n
    exact ⟨.mk fun n ↦ ⟨coeff n f, hcoeff n⟩, ext fun n ↦ by simp⟩
  · rintro ⟨g, rfl⟩
    exact le_v_iff.2 fun n ↦ (zero_le_addValuation_ratCast_iff _ _).2 <|
      (mem_pLocalInt_iff _).1 (coeff n g).2

end PowerSeries.Padic

namespace PowerSeries

/-- The p-adic valuations of the coefficients of a rational modular form are bounded below. -/
theorem isModularForm_v_ne_bot {k : ℤ} {f : ℚ⟦X⟧} (hf : f.isModularForm k) :
    Padic.v (f.map (algebraMap ℚ ℚ_[p])) ≠ ⊥ := by
  sorry

end PowerSeries
