/-
Copyright (c) 2026 Riccardo Brasca. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Riccardo Brasca
-/

module

public import PadicModForms.Rational.Graded
public import PadicModForms.Rational.Ramanujan

/-!
# The Serre derivative on rational modular forms

The operator `Θ = q d/dq` does not preserve modularity. Its correction

`δₖ f = Θ f - (k / 12) E₂ f`

does: it maps rational modular forms of weight `k` to rational modular forms of weight `k + 2`.
This file defines it and proves that.

Modularity is proved algebraically, from Ramanujan's identities in `Rational/Ramanujan.lean`. The
point is that the `E₂` term of each identity cancels against the correction term:

`3 δ E₄ = -E₆` and `2 δ E₆ = -E₄²`,

with no `E₂` left on the right. Since `δ` is a derivation of degree `2`, the forms whose Serre
derivative is again modular are closed under products; containing `E₄` and `E₆`, and the graded
ring being generated by those two (`rationalModularForms_natCast_eq_span`), they are everything.
Mathlib's analytic route to the same statement is still a `TODO` in
`Mathlib/NumberTheory/ModularForms/Derivative.lean`, and is not needed here.

## Main definitions

* `ModularForm.serreDerivAux`: `δₖ` as a `ℚ`-linear endomorphism of `ℚ⟦X⟧`.
* `ModularForm.serreDeriv`: `δₖ : rationalModularForms k →ₗ[ℚ] rationalModularForms (k + 2)`.

## Main results

* `ModularForm.serreDerivAux_mul`: the Leibniz rule, with the weights added.
* `ModularForm.serreDerivAux_E₄Rat`, `ModularForm.serreDerivAux_E₆Rat`: `δ` on the generators.
* `ModularForm.serreDerivAux_mem`: `δ` preserves modularity, raising the weight by `2`.
-/

noncomputable section

open PowerSeries EisensteinSeries PowerSeries SetLike

namespace ModularForm

variable {k l : ℤ} {f g : ℚ⟦X⟧}

/-- The Serre derivative on power series: `δₖ f = Θ f - (k / 12) E₂ f`. -/
public def serreDerivAux (k : ℤ) : ℚ⟦X⟧ →ₗ[ℚ] ℚ⟦X⟧ :=
  (Θ ℚ).toLinearMap - (k / 12 : ℚ) • LinearMap.mulLeft ℚ E₂Rat

public theorem serreDerivAux_apply (k : ℤ) (f : ℚ⟦X⟧) :
    serreDerivAux k f = Θ ℚ f - (k / 12 : ℚ) • (E₂Rat * f) := by
  simp [serreDerivAux]

/-- The Serre derivative is a derivation of degree `2` on the graded ring: it satisfies the
Leibniz rule with the weights added. -/
public theorem serreDerivAux_mul (k l : ℤ) (f g : ℚ⟦X⟧) :
    serreDerivAux (k + l) (f * g) = serreDerivAux k f * g + f * serreDerivAux l g := by
  grind [serreDerivAux_apply, Derivation.leibniz, smul_eq_mul, smul_eq_C_mul, Int.cast_add, add_div]

theorem serreDerivAux_one : serreDerivAux 0 (1 : ℚ⟦X⟧) = 0 := by
  simp [serreDerivAux_apply]

/-- Dividing by a nonzero natural number stays inside a `ℚ`-submodule. -/
theorem mem_of_natCast_mul_mem {n : ℕ} (hn : (n : ℚ) ≠ 0) {a : ℚ⟦X⟧} {S : Submodule ℚ ℚ⟦X⟧}
  (h : n * a ∈ S) : a ∈ S := by
  convert S.smul_mem (n : ℚ)⁻¹ h
  rw [smul_eq_C_mul, ← mul_assoc, ← map_natCast (C : ℚ →+* ℚ⟦X⟧) n, ← map_mul]
  simp [hn]

/-! ### The Serre derivative of the generators

The `E₂` term of each Ramanujan identity cancels against the correction term, leaving something
that no longer involves `E₂` — which is exactly why `δ` preserves modularity while `Θ` does not.
-/

/-- `3 δ E₄ = -E₆`. -/
public theorem serreDerivAux_E₄Rat : 3 * serreDerivAux 4 E₄Rat = -E₆Rat := by
  rw [serreDerivAux_apply, mul_sub, Θ_E₄Rat, smul_eq_C_mul, ← mul_assoc, ← map_ofNat C, ← map_mul]
  norm_num

/-- `2 δ E₆ = -E₄²`. -/
public theorem serreDerivAux_E₆Rat : 2 * serreDerivAux 6 E₆Rat = -(E₄Rat * E₄Rat) := by
  rw [serreDerivAux_apply, mul_sub, Θ_E₆Rat, smul_eq_C_mul, ← mul_assoc, ← map_ofNat C, ← map_mul]
  norm_num

theorem serreDerivAux_E₄Rat_mem : serreDerivAux 4 E₄Rat ∈ rationalModularForms 6 :=
  mem_of_natCast_mul_mem (n := 3) (by norm_num) (by simp [serreDerivAux_E₄Rat])

theorem serreDerivAux_E₆Rat_mem : serreDerivAux 6 (E₆Rat : ℚ⟦X⟧) ∈ rationalModularForms 8 :=
  mem_of_natCast_mul_mem (n := 2) (by norm_num) <| by
    rw [show ((2 : ℕ) : ℚ⟦X⟧) = 2 by norm_num, serreDerivAux_E₆Rat]
    exact neg_mem (by simpa using mul_mem_graded E₄Rat.2 E₄Rat.2)

/-! ### `δ` preserves modularity

`δ` is a degree-`2` derivation, so the forms whose Serre derivative is again modular are closed
under products. Since they contain `E₄` and `E₆`, and the graded ring is generated by those two,
they are everything.
-/

/-- Forms with modular Serre derivative are closed under products. -/
theorem serreDerivAux_mul_mem (hf : f ∈ rationalModularForms k) (hg : g ∈ rationalModularForms l)
    (hδf : serreDerivAux k f ∈ rationalModularForms (k + 2))
    (hδg : serreDerivAux l g ∈ rationalModularForms (l + 2)) :
    serreDerivAux (k + l) (f * g) ∈ rationalModularForms (k + l + 2) := by
  rw [serreDerivAux_mul]
  refine add_mem ?_ ?_
  · simpa [show k + 2 + l = k + l + 2 by ring] using mul_mem_graded hδf hg
  · simpa [show k + (l + 2) = k + l + 2 by ring] using mul_mem_graded hf hδg

/-- Forms with modular Serre derivative are closed under powers. -/
theorem serreDerivAux_pow_mem (hf : f ∈ rationalModularForms k)
    (hδf : serreDerivAux k f ∈ rationalModularForms (k + 2)) (n : ℕ) :
    serreDerivAux (n * k) (f ^ n) ∈ rationalModularForms (n * k + 2) := by
  induction n with
  | zero => simp [serreDerivAux_one]
  | succ m ih => simpa [show (m : ℤ) * k + k = (m + 1) * k by ring, pow_succ] using
      serreDerivAux_mul_mem (pow_mem_graded m hf) hf ih hδf

/-- The Serre derivative of a monomial in `E₄` and `E₆` is modular. -/
theorem serreDerivAux_monomial_mem {a b n : ℕ} (hab : 4 * a + 6 * b = n) :
    serreDerivAux n (E₄Rat ^ a * E₆Rat ^ b) ∈ rationalModularForms (n + 2) := by
  have h := serreDerivAux_mul_mem (pow_mem_graded a E₄Rat.2) (pow_mem_graded b E₆Rat.2)
    (serreDerivAux_pow_mem E₄Rat.2 serreDerivAux_E₄Rat_mem a)
    (serreDerivAux_pow_mem E₆Rat.2 serreDerivAux_E₆Rat_mem b)
  grind

/-- **The Serre derivative preserves modularity**: `δₖ` sends rational modular forms of weight `k`
to rational modular forms of weight `k + 2`. -/
public theorem serreDerivAux_mem (hf : f ∈ rationalModularForms k) :
    serreDerivAux k f ∈ rationalModularForms (k + 2) := by
  rcases lt_or_ge k 0 with hk | hk
  · rw [rationalModularForms_eq_bot_of_neg hk, Submodule.mem_bot] at hf
    simp [hf]
  · obtain ⟨n, rfl⟩ : ∃ n : ℕ, k = n := ⟨k.toNat, by lia⟩
    refine (?_ : rationalModularForms n ≤ (rationalModularForms (n + 2)).comap (serreDerivAux n)) hf
    rw [rationalModularForms_natCast_eq_span, Submodule.span_le]
    rintro _ ⟨a, b, hab, rfl⟩
    exact serreDerivAux_monomial_mem hab

/-! ### The Serre derivative as a map of modular forms -/

/-- The **Serre derivative** `δₖ f = Θ f - (k / 12) E₂ f` as a `ℚ`-linear map from rational
modular forms of weight `k` to rational modular forms of weight `k + 2`. -/
public def serreDeriv (k : ℤ) : rationalModularForms k →ₗ[ℚ] rationalModularForms (k + 2) :=
  (serreDerivAux k).restrict fun _ hf ↦ serreDerivAux_mem hf

@[simp]
public theorem coe_serreDeriv (k : ℤ) (f : rationalModularForms k) :
    serreDeriv k f = Θ ℚ f - (k / 12 : ℚ) • (E₂Rat * f) := by
  rw [serreDeriv, LinearMap.coe_restrict_apply, serreDerivAux_apply]

end ModularForm
