/-
Copyright (c) 2026 Riccardo Brasca. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Riccardo Brasca
-/

module

public import Mathlib.Algebra.Field.ZMod
public import Mathlib.Analysis.Normed.Field.Lemmas
public import Mathlib.Data.Nat.Prime.Int
public import Mathlib.RingTheory.DedekindDomain.AdicValuation
import Mathlib.Data.ZMod.Units
import Mathlib.RingTheory.Int.Basic

/-!
# The localization of `ℤ` at a prime number

We consider the prime ideal of `ℤ` generated by a prime number `p` as a height-one prime, define
the localization of `ℤ` at `p` as a valuation subring of `ℚ`, and construct the reduction map
to `ℤ/pℤ`.
-/

@[expose] public section

open Ideal IsDedekindDomain

variable {p : ℕ} [hp : Fact p.Prime]

-- should go to Mathlib.RingTheory.Int.Basic
instance isPrime_span_intCast : (span {(p : ℤ)}).IsPrime :=
  (span_singleton_prime (by exact_mod_cast hp.1.ne_zero)).2 (Nat.prime_iff_prime_int.1 hp.1)

variable (p)

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- The prime ideal of `ℤ` generated by `p`, as a height-one prime. -/
def heightOneSpec : HeightOneSpectrum ℤ where
  asIdeal := span {(p : ℤ)}
  isPrime := isPrime_span_intCast
  ne_bot := by simpa using hp.1.ne_zero

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- The localization of `ℤ` at the prime ideal generated by `p`, realized as a valuation
subring of `ℚ`. -/
noncomputable def pLocalInt : ValuationSubring ℚ := (heightOneSpec p).valuationSubringAtPrime ℚ

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
instance : IsLocalization.AtPrime (pLocalInt p) (span {(p : ℤ)}) :=
  inferInstanceAs (IsLocalization (heightOneSpec p).asIdeal.primeCompl
    ((heightOneSpec p).valuationSubringAtPrime ℚ))

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
theorem pLocalInt_eq_valuationSubring :
    pLocalInt p = ((heightOneSpec p).valuation ℚ).valuationSubring :=
  HeightOneSpectrum.valuationSubringAtPrime_eq_valuationSubring ..

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
theorem mem_pLocalInt_iff {q : ℚ} : q ∈ pLocalInt p ↔ ¬ p ∣ q.den := by
  rw [pLocalInt_eq_valuationSubring, Valuation.mem_valuationSubring_iff,
    Rat.valuation_le_one_iff_den]
  simp [heightOneSpec, mem_span_singleton, Int.natCast_dvd_natCast]

variable {p}

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- The reduction map from the localization of `ℤ` at the prime ideal generated by `p` to
`ℤ/pℤ`. -/
@[simps!]
noncomputable def pLocalInt.toZMod : pLocalInt p →+* ZMod p :=
  IsLocalization.lift (M := (span {(p : ℤ)}).primeCompl) (g := Int.castRingHom (ZMod p))
    fun y ↦ isUnit_iff_ne_zero.2 fun hy ↦
      y.2 (mem_span_singleton.2 ((ZMod.intCast_zmod_eq_zero_iff_dvd _ _).1 hy))

/-- The reduction map from the localization of `ℤ` at `p` to `ℤ/p^mℤ`. -/
noncomputable def pLocalInt.toZModPow (m : ℕ) : pLocalInt p →+* ZMod (p ^ m) :=
  IsLocalization.lift (M := (span {(p : ℤ)}).primeCompl)
    (g := Int.castRingHom (ZMod (p ^ m))) fun y ↦ by
      refine (ZMod.coe_int_isUnit_iff_isCoprime _ _).2 (Int.isCoprime_iff_nat_coprime.2 ?_)
      exact Nat.Coprime.pow_left _ <| hp.out.coprime_iff_not_dvd.mpr fun hpy ↦
        y.2 <| mem_span_singleton.2 (by rwa [Int.natCast_dvd])

@[simp]
theorem pLocalInt.toZModPow_pow (m : ℕ) : pLocalInt.toZModPow m ((p : pLocalInt p) ^ m) = 0 := by
  simp [map_natCast, ← Nat.cast_pow]

theorem pLocalInt.toZModPow_eq_zero_of_dvd {m : ℕ} {x : pLocalInt p}
  (hx : (p : pLocalInt p) ^ m ∣ x) : pLocalInt.toZModPow m x = 0 := by
  obtain ⟨y, rfl⟩ := hx
  rw [map_mul, pLocalInt.toZModPow_pow, zero_mul]
