/-
Copyright (c) 2026 Riccardo Brasca. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Riccardo Brasca
-/

module

public import Mathlib.Algebra.Field.ZMod
public import Mathlib.Analysis.Normed.Field.Lemmas
public import Mathlib.Data.Nat.Prime.Int
public import Mathlib.RingTheory.DedekindDomain.AdicValuation
import Mathlib.Data.ZMod.Units
import Mathlib.RingTheory.Int.Basic

/-!
# The localization of `ℤ` at a prime number

We consider the prime ideal of `ℤ` generated by a prime number `p` as a height-one prime, define
the localization of `ℤ` at `p` as a valuation subring of `ℚ`, and construct the reduction map
to `ℤ/pℤ`.
-/

@[expose] public section

open Ideal IsDedekindDomain

variable {p : ℕ} [hp : Fact p.Prime]

/-! ### The localization of `ℤ` at `p` -/

-- should go to Mathlib.RingTheory.Int.Basic
instance isPrime_span_intCast : (span {(p : ℤ)}).IsPrime :=
  (span_singleton_prime (by exact_mod_cast hp.1.ne_zero)).2 (Nat.prime_iff_prime_int.1 hp.1)

variable (p)

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- The prime ideal of `ℤ` generated by `p`, as a height-one prime. -/
def heightOneSpec : HeightOneSpectrum ℤ where
  asIdeal := span {(p : ℤ)}
  isPrime := isPrime_span_intCast
  ne_bot := by simpa using hp.1.ne_zero

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- The localization of `ℤ` at the prime ideal generated by `p`, realized as a valuation
subring of `ℚ`. -/
noncomputable def pLocalInt : ValuationSubring ℚ := (heightOneSpec p).valuationSubringAtPrime ℚ

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
instance : IsLocalization.AtPrime (pLocalInt p) (span {(p : ℤ)}) :=
  inferInstanceAs (IsLocalization (heightOneSpec p).asIdeal.primeCompl
    ((heightOneSpec p).valuationSubringAtPrime ℚ))

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
theorem pLocalInt_eq_valuationSubring :
    pLocalInt p = ((heightOneSpec p).valuation ℚ).valuationSubring :=
  HeightOneSpectrum.valuationSubringAtPrime_eq_valuationSubring ..

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
theorem mem_pLocalInt_iff {q : ℚ} : q ∈ pLocalInt p ↔ ¬ p ∣ q.den := by
  rw [pLocalInt_eq_valuationSubring, Valuation.mem_valuationSubring_iff,
    Rat.valuation_le_one_iff_den]
  simp [heightOneSpec, mem_span_singleton, Int.natCast_dvd_natCast]

variable {p}

-- should go to Mathlib.RingTheory.Valuation.ValuationSubring, for a general `ValuationSubring`
/-- Extension of scalars from `pLocalInt p` to `ℚ` is injective: it is the inclusion of a subring
of `ℚ`. -/
theorem pLocalInt.algebraMap_injective :
    Function.Injective (algebraMap (pLocalInt p) ℚ) := fun _ _ ↦ Subtype.ext

-- should go to Mathlib.Algebra.Ring.Subsemiring.Defs, for a general `SubsemiringClass`
/-- A numeral of `pLocalInt p` is the corresponding numeral of `ℚ`. -/
@[simp, norm_cast]
theorem pLocalInt.coe_ofNat (n : ℕ) [n.AtLeastTwo] :
    ((ofNat(n) : pLocalInt p) : ℚ) = OfNat.ofNat n :=
  map_ofNat (pLocalInt p).subtype n

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- The prime `p` is nonzero in `pLocalInt p`, which is a subring of `ℚ`. -/
@[simp]
theorem pLocalInt.natCast_ne_zero : (p : pLocalInt p) ≠ 0 := by
  simpa [Subtype.ext_iff] using hp.1.ne_zero

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- The inverse of a nonzero natural number prime to `p` is `p`-integral. -/
theorem inv_natCast_mem_pLocalInt {n : ℕ} (hn : n ≠ 0) (hpn : ¬ p ∣ n) :
    ((n : ℚ))⁻¹ ∈ pLocalInt p := by
  rwa [mem_pLocalInt_iff, ← one_div, show ((1 : ℚ) / n).den = n from by simp [hn]]

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- A finite sum of `p`-integral terms weighted by naturals divisible by `p` is `p` times a
`p`-integral rational. -/
theorem exists_sum_natCast_mul_eq_mul {ι : Type*} {s : Finset ι} {c : ι → ℕ} {b : ι → ℚ}
    (hc : ∀ i ∈ s, p ∣ c i) (hb : ∀ i ∈ s, b i ∈ pLocalInt p) :
    ∃ T ∈ pLocalInt p, ∑ i ∈ s, (c i : ℚ) * b i = p * T := by
  refine ⟨∑ i ∈ s, ((c i / p : ℕ) : ℚ) * b i,
    sum_mem fun i hi ↦ mul_mem (natCast_mem _ _) (hb i hi), ?_⟩
  rw [Finset.mul_sum]
  exact Finset.sum_congr rfl fun i hi ↦ by
    rw [← mul_assoc, ← Nat.cast_mul, Nat.mul_div_cancel' (hc i hi)]

/-! ### Reduction modulo powers of `p` -/

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- The reduction map from the localization of `ℤ` at the prime ideal generated by `p` to
`ℤ/pℤ`. -/
@[simps!]
noncomputable def pLocalInt.toZMod : pLocalInt p →+* ZMod p :=
  IsLocalization.lift (M := (span {(p : ℤ)}).primeCompl) (g := Int.castRingHom (ZMod p))
    fun y ↦ isUnit_iff_ne_zero.2 fun hy ↦
      y.2 (mem_span_singleton.2 ((ZMod.intCast_zmod_eq_zero_iff_dvd _ _).1 hy))

/-- The reduction map from the localization of `ℤ` at `p` to `ℤ/p^mℤ`. -/
@[simps!]
noncomputable def pLocalInt.toZModPow (m : ℕ) : pLocalInt p →+* ZMod (p ^ m) :=
  IsLocalization.lift (M := (span {(p : ℤ)}).primeCompl)
    (g := Int.castRingHom (ZMod (p ^ m))) fun y ↦ by
      refine (ZMod.coe_int_isUnit_iff_isCoprime _ _).2 (Int.isCoprime_iff_nat_coprime.2 ?_)
      exact Nat.Coprime.pow_left _ <| hp.out.coprime_iff_not_dvd.mpr fun hpy ↦
        y.2 <| mem_span_singleton.2 (by rwa [Int.natCast_dvd])

@[simp]
theorem pLocalInt.toZModPow_pow (m : ℕ) : pLocalInt.toZModPow m ((p : pLocalInt p) ^ m) = 0 := by
  simp [map_natCast, ← Nat.cast_pow]

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- Reduction modulo `p` is surjective. -/
theorem pLocalInt.toZMod_surjective : Function.Surjective (pLocalInt.toZMod (p := p)) :=
  fun z ↦ ⟨algebraMap ℤ (pLocalInt p) (z.val : ℤ), by simp [pLocalInt.toZMod]⟩

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- `p` generates the maximal ideal of the local ring `pLocalInt p`. -/
theorem pLocalInt.maximalIdeal_eq_span :
    IsLocalRing.maximalIdeal (pLocalInt p) = span {(p : pLocalInt p)} := by
  refine le_antisymm (fun y hy ↦ ?_) ?_
  · obtain ⟨x, s, rfl⟩ := IsLocalization.exists_mk'_eq (span {(p : ℤ)}).primeCompl y
    rw [IsLocalization.AtPrime.mk'_mem_maximal_iff (pLocalInt p) (span {(p : ℤ)}) x s,
      mem_span_singleton] at hy
    obtain ⟨b, rfl⟩ := hy
    rw [mem_span_singleton, IsLocalization.mk'_eq_mul_mk'_one]
    exact dvd_mul_of_dvd_left ⟨algebraMap ℤ (pLocalInt p) b, by push_cast; ring⟩ _
  · rw [span_le, Set.singleton_subset_iff, SetLike.mem_coe]
    simpa using (IsLocalization.AtPrime.to_map_mem_maximal_iff (pLocalInt p)
      (span {(p : ℤ)}) p).mpr (mem_span_singleton.mpr dvd_rfl)

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- Reduction modulo `p` is the residue map of the local ring `pLocalInt p`: being surjective
onto a field, its kernel is the maximal ideal. -/
theorem pLocalInt.ker_toZMod :
    RingHom.ker pLocalInt.toZMod = IsLocalRing.maximalIdeal (pLocalInt p) :=
  IsLocalRing.eq_maximalIdeal (RingHom.ker_isMaximal_of_surjective _ pLocalInt.toZMod_surjective)

theorem pLocalInt.ker_toZModPow (n : ℕ) :
    RingHom.ker (pLocalInt.toZModPow n) = span {(p : pLocalInt p) ^ n} := by
  ext y
  rw [RingHom.mem_ker, mem_span_singleton]
  obtain ⟨a, y, rfl⟩ := IsLocalization.exists_mk'_eq ((span {(p : ℤ)}).primeCompl) y
  rw [IsLocalization.mk'_eq_mul_mk'_one]
  simp only [algebraMap_int_eq, eq_intCast, map_mul, map_intCast]
  have h := isUnit_of_invertible (IsLocalization.mk' (↥(pLocalInt p)) 1 y)
  simp only [h.dvd_mul_right, ((toZModPow n).isUnit_map h).mul_left_eq_zero,
    ZMod.intCast_zmod_eq_zero_iff_dvd _ _, Nat.cast_pow]
  refine ⟨fun ⟨b, hb⟩ ↦ ⟨b, by rw [hb]; push_cast; ring⟩, fun ⟨b, hb⟩ ↦ ?_⟩
  obtain ⟨c, z, rfl⟩ := IsLocalization.exists_mk'_eq ((span {(p : ℤ)}).primeCompl) b
  have : (algebraMap ℤ (pLocalInt p)) a = (algebraMap ℤ ↥(pLocalInt p)) (p ^ n : ℤ) *
    IsLocalization.mk' (↥(pLocalInt p)) c z := by simp [hb]
  -- rw [← (IsLocalization.mk'_one (R := ℤ) (M := (span {(p : ℤ)}).primeCompl) (pLocalInt p)) a] at this
  rw [IsLocalization.mul_mk'_eq_mk'_of_mul (S := pLocalInt p) (p ^ n : ℤ) c z] at this
  rw [IsLocalization.eq_mk'_iff_mul_eq] at this
  rw [← map_mul] at this
  have hinj : Function.Injective ⇑(algebraMap ℤ ↥(pLocalInt p)) := by
    apply IsLocalization.injective (R := ℤ) (M := (span {(p : ℤ)}).primeCompl) (pLocalInt p)
    sorry
  have := hinj this
  have : ((p ^ n : ℕ) : ℤ) ∣ a * ↑z := by simp [this]
  rw [Int.natCast_dvd] at this
  rw [Int.natAbs_mul] at this
  have : ((p ^ n : ℕ) : ℤ) ∣ a := by
    rw [Int.natCast_dvd]
    refine Prime.pow_dvd_of_dvd_mul_right hp.out.prime n ?_ this
    sorry
  push_cast at this
  exact this

/-- An element of `pLocalInt p` killed by reduction modulo `p` is divisible by `p`. -/
theorem pLocalInt.dvd_of_toZMod_eq_zero {x : pLocalInt p} (hx : pLocalInt.toZMod x = 0) :
    (p : pLocalInt p) ∣ x := by
  rwa [← mem_span_singleton, ← pLocalInt.maximalIdeal_eq_span, ← pLocalInt.ker_toZMod]

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- A `p`-integral rational with nonzero reduction modulo `p` has a `p`-integral inverse. -/
theorem inv_mem_pLocalInt {x : ℚ} (hx : x ∈ pLocalInt p) (h : pLocalInt.toZMod ⟨x, hx⟩ ≠ 0) :
    x⁻¹ ∈ pLocalInt p := by
  obtain ⟨u, hu⟩ : IsUnit (⟨x, hx⟩ : pLocalInt p) :=
    IsLocalRing.notMem_maximalIdeal.mp (by rwa [← pLocalInt.ker_toZMod, RingHom.mem_ker])
  suffices x * ((u⁻¹ : (pLocalInt p)ˣ) : ℚ) = 1 by simp [inv_eq_of_mul_eq_one_right this]
  suffices (⟨x, hx⟩ : pLocalInt p) * ((u⁻¹ : (pLocalInt p)ˣ) : pLocalInt p) = 1 by
    simpa using congrArg Subtype.val this
  rw [← hu, ← Units.val_mul, mul_inv_cancel, Units.val_one]

theorem pLocalInt.toZModPow_eq_zero_of_dvd {m : ℕ} {x : pLocalInt p}
  (hx : (p : pLocalInt p) ^ m ∣ x) : pLocalInt.toZModPow m x = 0 := by
  obtain ⟨y, rfl⟩ := hx
  rw [map_mul, pLocalInt.toZModPow_pow, zero_mul]

/-- An element of `pLocalInt p` killed by reduction modulo `p ^ m` is divisible by `p ^ m`. -/
theorem pLocalInt.dvd_of_toZModPow_eq_zero {m : ℕ} {x : pLocalInt p}
    (hx : pLocalInt.toZModPow m x = 0) : (p : pLocalInt p) ^ m ∣ x := by
  rwa [← mem_span_singleton, ← pLocalInt.ker_toZModPow m]

-- should go to Mathlib.NumberTheory.Padics.HeightOneSpectrum
/-- The kernel of reduction modulo `p ^ m`: an element of `pLocalInt p` reduces to `0` exactly
when it is divisible by `p ^ m`. -/
theorem pLocalInt.toZModPow_eq_zero_iff {m : ℕ} {x : pLocalInt p} :
    pLocalInt.toZModPow m x = 0 ↔ (p : pLocalInt p) ^ m ∣ x :=
  ⟨fun h ↦ pLocalInt.dvd_of_toZModPow_eq_zero h, fun h ↦ pLocalInt.toZModPow_eq_zero_of_dvd h⟩

/-- Reduction modulo `p ^ m` refines reduction modulo `p`. -/
theorem pLocalInt.castHom_toZModPow {m : ℕ} (hm : 1 ≤ m) (x : pLocalInt p) :
    ZMod.castHom (dvd_pow_self p (by lia : m ≠ 0)) (ZMod p) (pLocalInt.toZModPow m x) =
      pLocalInt.toZMod x := by
  sorry
